// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datav.proto
package com.oxchains.bean.model;
public final class DataV {
  private DataV() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockChainInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BlockChainInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 height = 1;</code>
     */
    long getHeight();

    /**
     * <code>int64 txcount = 2;</code>
     */
    long getTxcount();

    /**
     * <code>repeated .XY xy = 3;</code>
     */
    java.util.List<DataV.XY> 
        getXyList();
    /**
     * <code>repeated .XY xy = 3;</code>
     */
    DataV.XY getXy(int index);
    /**
     * <code>repeated .XY xy = 3;</code>
     */
    int getXyCount();
    /**
     * <code>repeated .XY xy = 3;</code>
     */
    java.util.List<? extends DataV.XYOrBuilder> 
        getXyOrBuilderList();
    /**
     * <code>repeated .XY xy = 3;</code>
     */
    DataV.XYOrBuilder getXyOrBuilder(
        int index);

    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    java.util.List<DataV.ValueContent> 
        getValuecontentList();
    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    DataV.ValueContent getValuecontent(int index);
    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    int getValuecontentCount();
    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    java.util.List<? extends DataV.ValueContentOrBuilder> 
        getValuecontentOrBuilderList();
    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    DataV.ValueContentOrBuilder getValuecontentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code BlockChainInfo}
   */
  public  static final class BlockChainInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BlockChainInfo)
      BlockChainInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlockChainInfo.newBuilder() to construct.
    private BlockChainInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockChainInfo() {
      height_ = 0L;
      txcount_ = 0L;
      xy_ = java.util.Collections.emptyList();
      valuecontent_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockChainInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              height_ = input.readInt64();
              break;
            }
            case 16: {

              txcount_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                xy_ = new java.util.ArrayList<DataV.XY>();
                mutable_bitField0_ |= 0x00000004;
              }
              xy_.add(
                  input.readMessage(DataV.XY.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                valuecontent_ = new java.util.ArrayList<DataV.ValueContent>();
                mutable_bitField0_ |= 0x00000008;
              }
              valuecontent_.add(
                  input.readMessage(DataV.ValueContent.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          xy_ = java.util.Collections.unmodifiableList(xy_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          valuecontent_ = java.util.Collections.unmodifiableList(valuecontent_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataV.internal_static_BlockChainInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataV.internal_static_BlockChainInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataV.BlockChainInfo.class, DataV.BlockChainInfo.Builder.class);
    }

    private int bitField0_;
    public static final int HEIGHT_FIELD_NUMBER = 1;
    private long height_;
    /**
     * <code>int64 height = 1;</code>
     */
    public long getHeight() {
      return height_;
    }

    public static final int TXCOUNT_FIELD_NUMBER = 2;
    private long txcount_;
    /**
     * <code>int64 txcount = 2;</code>
     */
    public long getTxcount() {
      return txcount_;
    }

    public static final int XY_FIELD_NUMBER = 3;
    private java.util.List<DataV.XY> xy_;
    /**
     * <code>repeated .XY xy = 3;</code>
     */
    public java.util.List<DataV.XY> getXyList() {
      return xy_;
    }
    /**
     * <code>repeated .XY xy = 3;</code>
     */
    public java.util.List<? extends DataV.XYOrBuilder> 
        getXyOrBuilderList() {
      return xy_;
    }
    /**
     * <code>repeated .XY xy = 3;</code>
     */
    public int getXyCount() {
      return xy_.size();
    }
    /**
     * <code>repeated .XY xy = 3;</code>
     */
    public DataV.XY getXy(int index) {
      return xy_.get(index);
    }
    /**
     * <code>repeated .XY xy = 3;</code>
     */
    public DataV.XYOrBuilder getXyOrBuilder(
        int index) {
      return xy_.get(index);
    }

    public static final int VALUECONTENT_FIELD_NUMBER = 4;
    private java.util.List<DataV.ValueContent> valuecontent_;
    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    public java.util.List<DataV.ValueContent> getValuecontentList() {
      return valuecontent_;
    }
    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    public java.util.List<? extends DataV.ValueContentOrBuilder> 
        getValuecontentOrBuilderList() {
      return valuecontent_;
    }
    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    public int getValuecontentCount() {
      return valuecontent_.size();
    }
    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    public DataV.ValueContent getValuecontent(int index) {
      return valuecontent_.get(index);
    }
    /**
     * <code>repeated .ValueContent valuecontent = 4;</code>
     */
    public DataV.ValueContentOrBuilder getValuecontentOrBuilder(
        int index) {
      return valuecontent_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (height_ != 0L) {
        output.writeInt64(1, height_);
      }
      if (txcount_ != 0L) {
        output.writeInt64(2, txcount_);
      }
      for (int i = 0; i < xy_.size(); i++) {
        output.writeMessage(3, xy_.get(i));
      }
      for (int i = 0; i < valuecontent_.size(); i++) {
        output.writeMessage(4, valuecontent_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (height_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, height_);
      }
      if (txcount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, txcount_);
      }
      for (int i = 0; i < xy_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, xy_.get(i));
      }
      for (int i = 0; i < valuecontent_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, valuecontent_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataV.BlockChainInfo)) {
        return super.equals(obj);
      }
      DataV.BlockChainInfo other = (DataV.BlockChainInfo) obj;

      boolean result = true;
      result = result && (getHeight()
          == other.getHeight());
      result = result && (getTxcount()
          == other.getTxcount());
      result = result && getXyList()
          .equals(other.getXyList());
      result = result && getValuecontentList()
          .equals(other.getValuecontentList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeight());
      hash = (37 * hash) + TXCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTxcount());
      if (getXyCount() > 0) {
        hash = (37 * hash) + XY_FIELD_NUMBER;
        hash = (53 * hash) + getXyList().hashCode();
      }
      if (getValuecontentCount() > 0) {
        hash = (37 * hash) + VALUECONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getValuecontentList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataV.BlockChainInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataV.BlockChainInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataV.BlockChainInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataV.BlockChainInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataV.BlockChainInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataV.BlockChainInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataV.BlockChainInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataV.BlockChainInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataV.BlockChainInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataV.BlockChainInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataV.BlockChainInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataV.BlockChainInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataV.BlockChainInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BlockChainInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BlockChainInfo)
        DataV.BlockChainInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataV.internal_static_BlockChainInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataV.internal_static_BlockChainInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataV.BlockChainInfo.class, DataV.BlockChainInfo.Builder.class);
      }

      // Construct using DataV.BlockChainInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getXyFieldBuilder();
          getValuecontentFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        height_ = 0L;

        txcount_ = 0L;

        if (xyBuilder_ == null) {
          xy_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          xyBuilder_.clear();
        }
        if (valuecontentBuilder_ == null) {
          valuecontent_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          valuecontentBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataV.internal_static_BlockChainInfo_descriptor;
      }

      public DataV.BlockChainInfo getDefaultInstanceForType() {
        return DataV.BlockChainInfo.getDefaultInstance();
      }

      public DataV.BlockChainInfo build() {
        DataV.BlockChainInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DataV.BlockChainInfo buildPartial() {
        DataV.BlockChainInfo result = new DataV.BlockChainInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.height_ = height_;
        result.txcount_ = txcount_;
        if (xyBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            xy_ = java.util.Collections.unmodifiableList(xy_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.xy_ = xy_;
        } else {
          result.xy_ = xyBuilder_.build();
        }
        if (valuecontentBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            valuecontent_ = java.util.Collections.unmodifiableList(valuecontent_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.valuecontent_ = valuecontent_;
        } else {
          result.valuecontent_ = valuecontentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataV.BlockChainInfo) {
          return mergeFrom((DataV.BlockChainInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataV.BlockChainInfo other) {
        if (other == DataV.BlockChainInfo.getDefaultInstance()) return this;
        if (other.getHeight() != 0L) {
          setHeight(other.getHeight());
        }
        if (other.getTxcount() != 0L) {
          setTxcount(other.getTxcount());
        }
        if (xyBuilder_ == null) {
          if (!other.xy_.isEmpty()) {
            if (xy_.isEmpty()) {
              xy_ = other.xy_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureXyIsMutable();
              xy_.addAll(other.xy_);
            }
            onChanged();
          }
        } else {
          if (!other.xy_.isEmpty()) {
            if (xyBuilder_.isEmpty()) {
              xyBuilder_.dispose();
              xyBuilder_ = null;
              xy_ = other.xy_;
              bitField0_ = (bitField0_ & ~0x00000004);
              xyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getXyFieldBuilder() : null;
            } else {
              xyBuilder_.addAllMessages(other.xy_);
            }
          }
        }
        if (valuecontentBuilder_ == null) {
          if (!other.valuecontent_.isEmpty()) {
            if (valuecontent_.isEmpty()) {
              valuecontent_ = other.valuecontent_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureValuecontentIsMutable();
              valuecontent_.addAll(other.valuecontent_);
            }
            onChanged();
          }
        } else {
          if (!other.valuecontent_.isEmpty()) {
            if (valuecontentBuilder_.isEmpty()) {
              valuecontentBuilder_.dispose();
              valuecontentBuilder_ = null;
              valuecontent_ = other.valuecontent_;
              bitField0_ = (bitField0_ & ~0x00000008);
              valuecontentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getValuecontentFieldBuilder() : null;
            } else {
              valuecontentBuilder_.addAllMessages(other.valuecontent_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataV.BlockChainInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataV.BlockChainInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long height_ ;
      /**
       * <code>int64 height = 1;</code>
       */
      public long getHeight() {
        return height_;
      }
      /**
       * <code>int64 height = 1;</code>
       */
      public Builder setHeight(long value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 height = 1;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0L;
        onChanged();
        return this;
      }

      private long txcount_ ;
      /**
       * <code>int64 txcount = 2;</code>
       */
      public long getTxcount() {
        return txcount_;
      }
      /**
       * <code>int64 txcount = 2;</code>
       */
      public Builder setTxcount(long value) {
        
        txcount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 txcount = 2;</code>
       */
      public Builder clearTxcount() {
        
        txcount_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<DataV.XY> xy_ =
        java.util.Collections.emptyList();
      private void ensureXyIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          xy_ = new java.util.ArrayList<DataV.XY>(xy_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DataV.XY, DataV.XY.Builder, DataV.XYOrBuilder> xyBuilder_;

      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public java.util.List<DataV.XY> getXyList() {
        if (xyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(xy_);
        } else {
          return xyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public int getXyCount() {
        if (xyBuilder_ == null) {
          return xy_.size();
        } else {
          return xyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public DataV.XY getXy(int index) {
        if (xyBuilder_ == null) {
          return xy_.get(index);
        } else {
          return xyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public Builder setXy(
          int index, DataV.XY value) {
        if (xyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureXyIsMutable();
          xy_.set(index, value);
          onChanged();
        } else {
          xyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public Builder setXy(
          int index, DataV.XY.Builder builderForValue) {
        if (xyBuilder_ == null) {
          ensureXyIsMutable();
          xy_.set(index, builderForValue.build());
          onChanged();
        } else {
          xyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public Builder addXy(DataV.XY value) {
        if (xyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureXyIsMutable();
          xy_.add(value);
          onChanged();
        } else {
          xyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public Builder addXy(
          int index, DataV.XY value) {
        if (xyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureXyIsMutable();
          xy_.add(index, value);
          onChanged();
        } else {
          xyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public Builder addXy(
          DataV.XY.Builder builderForValue) {
        if (xyBuilder_ == null) {
          ensureXyIsMutable();
          xy_.add(builderForValue.build());
          onChanged();
        } else {
          xyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public Builder addXy(
          int index, DataV.XY.Builder builderForValue) {
        if (xyBuilder_ == null) {
          ensureXyIsMutable();
          xy_.add(index, builderForValue.build());
          onChanged();
        } else {
          xyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public Builder addAllXy(
          java.lang.Iterable<? extends DataV.XY> values) {
        if (xyBuilder_ == null) {
          ensureXyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, xy_);
          onChanged();
        } else {
          xyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public Builder clearXy() {
        if (xyBuilder_ == null) {
          xy_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          xyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public Builder removeXy(int index) {
        if (xyBuilder_ == null) {
          ensureXyIsMutable();
          xy_.remove(index);
          onChanged();
        } else {
          xyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public DataV.XY.Builder getXyBuilder(
          int index) {
        return getXyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public DataV.XYOrBuilder getXyOrBuilder(
          int index) {
        if (xyBuilder_ == null) {
          return xy_.get(index);  } else {
          return xyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public java.util.List<? extends DataV.XYOrBuilder> 
           getXyOrBuilderList() {
        if (xyBuilder_ != null) {
          return xyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(xy_);
        }
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public DataV.XY.Builder addXyBuilder() {
        return getXyFieldBuilder().addBuilder(
            DataV.XY.getDefaultInstance());
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public DataV.XY.Builder addXyBuilder(
          int index) {
        return getXyFieldBuilder().addBuilder(
            index, DataV.XY.getDefaultInstance());
      }
      /**
       * <code>repeated .XY xy = 3;</code>
       */
      public java.util.List<DataV.XY.Builder> 
           getXyBuilderList() {
        return getXyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DataV.XY, DataV.XY.Builder, DataV.XYOrBuilder> 
          getXyFieldBuilder() {
        if (xyBuilder_ == null) {
          xyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DataV.XY, DataV.XY.Builder, DataV.XYOrBuilder>(
                  xy_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          xy_ = null;
        }
        return xyBuilder_;
      }

      private java.util.List<DataV.ValueContent> valuecontent_ =
        java.util.Collections.emptyList();
      private void ensureValuecontentIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          valuecontent_ = new java.util.ArrayList<DataV.ValueContent>(valuecontent_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DataV.ValueContent, DataV.ValueContent.Builder, DataV.ValueContentOrBuilder> valuecontentBuilder_;

      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public java.util.List<DataV.ValueContent> getValuecontentList() {
        if (valuecontentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(valuecontent_);
        } else {
          return valuecontentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public int getValuecontentCount() {
        if (valuecontentBuilder_ == null) {
          return valuecontent_.size();
        } else {
          return valuecontentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public DataV.ValueContent getValuecontent(int index) {
        if (valuecontentBuilder_ == null) {
          return valuecontent_.get(index);
        } else {
          return valuecontentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public Builder setValuecontent(
          int index, DataV.ValueContent value) {
        if (valuecontentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuecontentIsMutable();
          valuecontent_.set(index, value);
          onChanged();
        } else {
          valuecontentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public Builder setValuecontent(
          int index, DataV.ValueContent.Builder builderForValue) {
        if (valuecontentBuilder_ == null) {
          ensureValuecontentIsMutable();
          valuecontent_.set(index, builderForValue.build());
          onChanged();
        } else {
          valuecontentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public Builder addValuecontent(DataV.ValueContent value) {
        if (valuecontentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuecontentIsMutable();
          valuecontent_.add(value);
          onChanged();
        } else {
          valuecontentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public Builder addValuecontent(
          int index, DataV.ValueContent value) {
        if (valuecontentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuecontentIsMutable();
          valuecontent_.add(index, value);
          onChanged();
        } else {
          valuecontentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public Builder addValuecontent(
          DataV.ValueContent.Builder builderForValue) {
        if (valuecontentBuilder_ == null) {
          ensureValuecontentIsMutable();
          valuecontent_.add(builderForValue.build());
          onChanged();
        } else {
          valuecontentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public Builder addValuecontent(
          int index, DataV.ValueContent.Builder builderForValue) {
        if (valuecontentBuilder_ == null) {
          ensureValuecontentIsMutable();
          valuecontent_.add(index, builderForValue.build());
          onChanged();
        } else {
          valuecontentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public Builder addAllValuecontent(
          java.lang.Iterable<? extends DataV.ValueContent> values) {
        if (valuecontentBuilder_ == null) {
          ensureValuecontentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, valuecontent_);
          onChanged();
        } else {
          valuecontentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public Builder clearValuecontent() {
        if (valuecontentBuilder_ == null) {
          valuecontent_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          valuecontentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public Builder removeValuecontent(int index) {
        if (valuecontentBuilder_ == null) {
          ensureValuecontentIsMutable();
          valuecontent_.remove(index);
          onChanged();
        } else {
          valuecontentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public DataV.ValueContent.Builder getValuecontentBuilder(
          int index) {
        return getValuecontentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public DataV.ValueContentOrBuilder getValuecontentOrBuilder(
          int index) {
        if (valuecontentBuilder_ == null) {
          return valuecontent_.get(index);  } else {
          return valuecontentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public java.util.List<? extends DataV.ValueContentOrBuilder> 
           getValuecontentOrBuilderList() {
        if (valuecontentBuilder_ != null) {
          return valuecontentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(valuecontent_);
        }
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public DataV.ValueContent.Builder addValuecontentBuilder() {
        return getValuecontentFieldBuilder().addBuilder(
            DataV.ValueContent.getDefaultInstance());
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public DataV.ValueContent.Builder addValuecontentBuilder(
          int index) {
        return getValuecontentFieldBuilder().addBuilder(
            index, DataV.ValueContent.getDefaultInstance());
      }
      /**
       * <code>repeated .ValueContent valuecontent = 4;</code>
       */
      public java.util.List<DataV.ValueContent.Builder> 
           getValuecontentBuilderList() {
        return getValuecontentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DataV.ValueContent, DataV.ValueContent.Builder, DataV.ValueContentOrBuilder> 
          getValuecontentFieldBuilder() {
        if (valuecontentBuilder_ == null) {
          valuecontentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DataV.ValueContent, DataV.ValueContent.Builder, DataV.ValueContentOrBuilder>(
                  valuecontent_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          valuecontent_ = null;
        }
        return valuecontentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BlockChainInfo)
    }

    // @@protoc_insertion_point(class_scope:BlockChainInfo)
    private static final DataV.BlockChainInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataV.BlockChainInfo();
    }

    public static DataV.BlockChainInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockChainInfo>
        PARSER = new com.google.protobuf.AbstractParser<BlockChainInfo>() {
      public BlockChainInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlockChainInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockChainInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockChainInfo> getParserForType() {
      return PARSER;
    }

    public DataV.BlockChainInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface XYOrBuilder extends
      // @@protoc_insertion_point(interface_extends:XY)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string x = 1;</code>
     */
    java.lang.String getX();
    /**
     * <code>string x = 1;</code>
     */
    com.google.protobuf.ByteString
        getXBytes();

    /**
     * <code>int64 y = 2;</code>
     */
    long getY();
  }
  /**
   * Protobuf type {@code XY}
   */
  public  static final class XY extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:XY)
      XYOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use XY.newBuilder() to construct.
    private XY(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private XY() {
      x_ = "";
      y_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private XY(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              x_ = s;
              break;
            }
            case 16: {

              y_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataV.internal_static_XY_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataV.internal_static_XY_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataV.XY.class, DataV.XY.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private volatile java.lang.Object x_;
    /**
     * <code>string x = 1;</code>
     */
    public java.lang.String getX() {
      java.lang.Object ref = x_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        x_ = s;
        return s;
      }
    }
    /**
     * <code>string x = 1;</code>
     */
    public com.google.protobuf.ByteString
        getXBytes() {
      java.lang.Object ref = x_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        x_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int Y_FIELD_NUMBER = 2;
    private long y_;
    /**
     * <code>int64 y = 2;</code>
     */
    public long getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getXBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, x_);
      }
      if (y_ != 0L) {
        output.writeInt64(2, y_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getXBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, x_);
      }
      if (y_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataV.XY)) {
        return super.equals(obj);
      }
      DataV.XY other = (DataV.XY) obj;

      boolean result = true;
      result = result && getX()
          .equals(other.getX());
      result = result && (getY()
          == other.getY());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX().hashCode();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getY());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataV.XY parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataV.XY parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataV.XY parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataV.XY parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataV.XY parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataV.XY parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataV.XY parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataV.XY parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataV.XY parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataV.XY parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataV.XY parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataV.XY parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataV.XY prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code XY}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:XY)
        DataV.XYOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataV.internal_static_XY_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataV.internal_static_XY_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataV.XY.class, DataV.XY.Builder.class);
      }

      // Construct using DataV.XY.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = "";

        y_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataV.internal_static_XY_descriptor;
      }

      public DataV.XY getDefaultInstanceForType() {
        return DataV.XY.getDefaultInstance();
      }

      public DataV.XY build() {
        DataV.XY result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DataV.XY buildPartial() {
        DataV.XY result = new DataV.XY(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataV.XY) {
          return mergeFrom((DataV.XY)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataV.XY other) {
        if (other == DataV.XY.getDefaultInstance()) return this;
        if (!other.getX().isEmpty()) {
          x_ = other.x_;
          onChanged();
        }
        if (other.getY() != 0L) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataV.XY parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataV.XY) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object x_ = "";
      /**
       * <code>string x = 1;</code>
       */
      public java.lang.String getX() {
        java.lang.Object ref = x_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          x_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string x = 1;</code>
       */
      public com.google.protobuf.ByteString
          getXBytes() {
        java.lang.Object ref = x_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          x_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string x = 1;</code>
       */
      public Builder setX(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = getDefaultInstance().getX();
        onChanged();
        return this;
      }
      /**
       * <code>string x = 1;</code>
       */
      public Builder setXBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        x_ = value;
        onChanged();
        return this;
      }

      private long y_ ;
      /**
       * <code>int64 y = 2;</code>
       */
      public long getY() {
        return y_;
      }
      /**
       * <code>int64 y = 2;</code>
       */
      public Builder setY(long value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:XY)
    }

    // @@protoc_insertion_point(class_scope:XY)
    private static final DataV.XY DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataV.XY();
    }

    public static DataV.XY getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<XY>
        PARSER = new com.google.protobuf.AbstractParser<XY>() {
      public XY parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new XY(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<XY> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<XY> getParserForType() {
      return PARSER;
    }

    public DataV.XY getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValueContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ValueContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code ValueContent}
   */
  public  static final class ValueContent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ValueContent)
      ValueContentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValueContent.newBuilder() to construct.
    private ValueContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValueContent() {
      value_ = "";
      content_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValueContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataV.internal_static_ValueContent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataV.internal_static_ValueContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataV.ValueContent.class, DataV.ValueContent.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataV.ValueContent)) {
        return super.equals(obj);
      }
      DataV.ValueContent other = (DataV.ValueContent) obj;

      boolean result = true;
      result = result && getValue()
          .equals(other.getValue());
      result = result && getContent()
          .equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataV.ValueContent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataV.ValueContent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataV.ValueContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataV.ValueContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataV.ValueContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataV.ValueContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataV.ValueContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataV.ValueContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataV.ValueContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataV.ValueContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataV.ValueContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataV.ValueContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataV.ValueContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ValueContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ValueContent)
        DataV.ValueContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataV.internal_static_ValueContent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataV.internal_static_ValueContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataV.ValueContent.class, DataV.ValueContent.Builder.class);
      }

      // Construct using DataV.ValueContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = "";

        content_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataV.internal_static_ValueContent_descriptor;
      }

      public DataV.ValueContent getDefaultInstanceForType() {
        return DataV.ValueContent.getDefaultInstance();
      }

      public DataV.ValueContent build() {
        DataV.ValueContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DataV.ValueContent buildPartial() {
        DataV.ValueContent result = new DataV.ValueContent(this);
        result.value_ = value_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataV.ValueContent) {
          return mergeFrom((DataV.ValueContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataV.ValueContent other) {
        if (other == DataV.ValueContent.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataV.ValueContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataV.ValueContent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ValueContent)
    }

    // @@protoc_insertion_point(class_scope:ValueContent)
    private static final DataV.ValueContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataV.ValueContent();
    }

    public static DataV.ValueContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValueContent>
        PARSER = new com.google.protobuf.AbstractParser<ValueContent>() {
      public ValueContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ValueContent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValueContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValueContent> getParserForType() {
      return PARSER;
    }

    public DataV.ValueContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlockChainInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlockChainInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_XY_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_XY_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValueContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValueContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013datav.proto\"g\n\016BlockChainInfo\022\016\n\006heigh" +
      "t\030\001 \001(\003\022\017\n\007txcount\030\002 \001(\003\022\017\n\002xy\030\003 \003(\0132\003.X" +
      "Y\022#\n\014valuecontent\030\004 \003(\0132\r.ValueContent\"\032" +
      "\n\002XY\022\t\n\001x\030\001 \001(\t\022\t\n\001y\030\002 \001(\003\".\n\014ValueConte" +
      "nt\022\r\n\005value\030\001 \001(\t\022\017\n\007content\030\002 \001(\tB\007B\005Da" +
      "taVb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BlockChainInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BlockChainInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlockChainInfo_descriptor,
        new java.lang.String[] { "Height", "Txcount", "Xy", "Valuecontent", });
    internal_static_XY_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_XY_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_XY_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_ValueContent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ValueContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValueContent_descriptor,
        new java.lang.String[] { "Value", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
