// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloOrderer.proto

package com.oxchains.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.oxchains.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   */
  String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
